SRCS :=
SRCS += x11_canvas
SRCS += x11_icon
SRCS += x11_graphics_system_x11

LIBNAME := backend_x11_native

CXXFLAGS += -I../backend_x11_common -I../common

include ../config.mk
include ../static_library.mk
