SRCS :=
# SRCS += main_actions
# SRCS += mode_simple
# SRCS += monitor
# SRCS += widget
# SRCS += child_widget
# SRCS += workspace
# SRCS += container
# SRCS += client
# SRCS += container_container
# SRCS += client_container
# SRCS += action_set
# SRCS += container_container_layout
# SRCS += client_container_layout
# SRCS += client_util
SRCS += application
# SRCS += container_util
# SRCS += mode_default
# SRCS += mode_3pane
# SRCS += window_manager_default
# SRCS += window_manager_3panel
# SRCS += shortcut_set
# SRCS += mouse_handler

LIBNAME := frontend

CXXFLAGS += -I../common

include ../config.mk
include ../static_library.mk
