TOP_DIR = ..

SRCS :=
SRCS += x11_canvas
SRCS += x11_icon
SRCS += x11_graphics_system_x11

LIBNAME := backend_x11_native

CXXFLAGS += -I$(TOP_DIR)/backend_x11_common -I$(TOP_DIR)/common

include $(TOP_DIR)/static_library.mk
