TOP_DIR = ..

SRCS += mode_simple
# SRCS += mode_default
# SRCS += mode_3pane
# SRCS += window_manager_default
# SRCS += window_manager_3panel

LIBNAME := frontend_modes

CXXFLAGS += -I$(TOP_DIR)/common
CXXFLAGS += -I$(TOP_DIR)/frontend
CXXFLAGS += -I$(TOP_DIR)/frontend_container
CXXFLAGS += -I$(TOP_DIR)/frontend_container_container

include $(TOP_DIR)/static_library.mk
