SRCS :=
SRCS += x11_widget_backend
SRCS += x11_widget
SRCS += x11_server_widget
SRCS += x11_client_widget
SRCS += x11_client
# SRCS += x11_shortcut_set
SRCS += x11_application
SRCS += x11_global

LIBNAME := backend_x11

CXXFLAGS += -I../backend_x11_common -I../common

include ../config.mk
include ../static_library.mk
