TOP_DIR = ..

SRCS += container_util
SRCS += container
SRCS += container_container
SRCS += client_container
SRCS += container_container_layout
SRCS += client_container_layout
SRCS += theme
SRCS += mouse_handler


LIBNAME := frontend_layout_box

CXXFLAGS += -I$(TOP_DIR)/common -I$(TOP_DIR)/frontend

include $(TOP_DIR)/static_library.mk
