TOP_DIR = ..

SRCS :=
SRCS += container_util
SRCS += container_container
SRCS += container_container_layout
SRCS += theme

LIBNAME := frontend_container_container

CXXFLAGS += -I$(TOP_DIR)/common -I$(TOP_DIR)/frontend -I$(TOP_DIR)/frontend_container

include $(TOP_DIR)/static_library.mk
