SRCS :=
# SRCS += mouse_handler
SRCS += shortcut_set
SRCS += config
SRCS += string_util
# SRCS += container_container_layout
# SRCS += client_container_layout
SRCS += theme
# SRCS += client_util
# SRCS += application
# SRCS += container_util
# SRCS += mode_default
# SRCS += mode_3pane
SRCS += cairo_canvas
SRCS += cairo_icon
# SRCS += window_manager_default
# SRCS += window_manager_3panel

include ../config.mk
include ../static_library.mk
