TOP_DIR = ..

SRCS :=
SRCS += x11_graphics_system_cairo

LIBNAME := backend_x11_cairo

CXXFLAGS += -I$(TOP_DIR)/backend_x11_common -I$(TOP_DIR)/common_cairo -I$(TOP_DIR)/common

include $(TOP_DIR)/static_library.mk
