TOP_DIR = ..

SRCS :=
SRCS += container
SRCS += client_container
SRCS += client_container_layout
SRCS += theme
SRCS += mouse_handler

LIBNAME := frontend_container

CXXFLAGS += -I$(TOP_DIR)/common -I$(TOP_DIR)/frontend

include $(TOP_DIR)/static_library.mk
